### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by olibos** [enkelmedia/Umbraco7-SeoVisualizer#12]
Could be great to add labels in XML to allow translations.

If you're intersted I can make a PR for that 😉

**Comment by enkelmedia** [comment]
Hi!

Oh! That is true! This started as a demo on a community-event and could use some TLC, if you are up for the PR you are more than welcome to do it! 

You know about to put translations in a “Lang”-folder in the package right?

**Comment by olibos** [comment]
Hello,

Yes, I know. I'll make a small PR for this 😉

**Comment by olibos** [comment]
Let me know if it's good for you...
