### ISSUE TITLE
Issue rendering in v8

### ISSUE THREAD

**Issue by amirkhan81** [enkelmedia/Umbraco7-SeoVisualizer#15]
Based on the documentation on Our I'm trying to render the SEO fields using the following:
@{ var seo = this.Model.GetPropertyValue<SeoValues>("seo"); }

But returns this error. Is there an @using or something I'm supposed to be including?

CS0246: The type or namespace name 'SeoValues' could not be found (are you missing a using directive or an assembly reference?)

**Comment by enkelmedia** [comment]
Hi!

The models is in the `SeoVisualizer`-namespace so you might need to include that in your using statement to include this namespace assuming that you code uses the T-parameters for the GetPropertyValue.

Something like:
```csharp
@(this.Model.Content.GetPropertyValue<SeoValues>("seo").Description)
```

**Comment by amirkhan81** [comment]
This works, thanks for your help.

```
@using SeoVisualizer
@{ var seo = Model.Value<SeoValues>("seo"); }

<title>@seo.Title</title> 
```

**Comment by enkelmedia** [comment]
Great news! I'll close the issue. 

Cheers!
