### ISSUE TITLE
Questions on its usage

### ISSUE THREAD

**Issue by akeilox** [enkelmedia/Umbraco7-SeoVisualizer#2]
I came across this and was excited about the use-case for editors to preview and edit SEO title and description with preview.
However when i try to use the code as specified (the second one), it throws error as below. This code is on a template (umbraco 7.1.6); The property is named seo in the assigned page.

Compiler Error Message: CS1061: 'object' does not contain a definition for 'Title' and no extension method 'Title' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)

Source Error:
Line 28: @{ var seo = this.Model.Content.GetPropertyValue("seo"); }
Line 29: 
Line 30: @seo.Title @seo.Description

**Comment by CodeAbuser** [comment]
I'm getting the same error. when i just output @seo i see { "title": "SEO title", "description": "this is the description" }  on the page, but it looks like @seo.Title throws an error. is there a using statement or something that i'm missing?

**Comment by enkelmedia** [comment]
Hi!

Try this.Model.Content.GetPropertyValue<SeoValues>("seo").Description

Does that work?

**Comment by CodeAbuser** [comment]
using that gives me this error:

 'object' does not contain a definition for 'Description' and no extension method 'Description' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)

**Comment by CodeAbuser** [comment]
if anybody else tries to use this and has the same issue, here's the solution:

add using statements to your view:

@using Umbraco.Web
@using Newtonsoft.Json.Linq

then parse the object to JObject:

var seo = JObject.Parse(this.Model.Content.GetPropertyValue("seo").ToString());

then get the values like this:

@seo.GetValue("title")
@seo.GetValue("description")

**Comment by rossiter10** [comment]
CodeAbuser's solution works, just make sure to check for empty values first(and remember those using statements!). Here's what I did, but you probably should set the value as a variable first so you don't have to get it twice...
if (!String.IsNullOrEmpty(this.Model.Content.GetPropertyValue("seo").ToString()))
{
	var seo = JObject.Parse(this.Model.Content.GetPropertyValue("seo").ToString());
	<meta name="title" content="@seo.GetValue("title")">
	<meta name="description" content="@seo.GetValue("description")">
}

**Comment by enkelmedia** [comment]
Hi!

Since we added the property value converters you can use it like this:

@(this.Model.Content.GetPropertyValue<SeoValues>("seo").Description)

or like this

@{ var seo = this.Model.Content.GetPropertyValue<SeoValues>("seo"); }


@seo.Description
@seo.Title


The <SeoValues>-part of the lines where stripped from documentation (readme.md) by github so I hade to change them to &gt; och &lt;

Hope this helps!

**Comment by CodeAbuser** [comment]
does this require downloading a new version or can i use this now?  What using statement do i need to be able to resolve the SeoValues object?

**Comment by enkelmedia** [comment]
You should be able to use the current version. Just include the namespace "SeoVisualizer"

**Comment by CodeAbuser** [comment]
@using SeoVisualizer;

That gives me an error. namespace not found

**Comment by enkelmedia** [comment]
Strange - do you have the dll in the bin-folder? If not - download the latest version from our.umbraco.org and install it again.

**Comment by CodeAbuser** [comment]
i did not have the dll. i upgraded to the latest version and the dll is there now and your example works. thanks!
