### ISSUE TITLE
Umbraco 14 compatibility

### ISSUE THREAD

**Issue by amirkhan81** [enkelmedia/Umbraco7-SeoVisualizer#30]
I'm getting build errors after installing the 13 version on a fresh 14 install. Are there any plans for a v14 compatible version? Installing using dotnet add package UmbracoSeoVisualizer did not throw an errors.

**Comment by enkelmedia** [comment]
Hi! 

It make sense since v14 has a totally re-written backoffice. I will update this plugin for v14 but I'm currently very busy so I can't really give any promises as to when.
 
I will keep you posted.

// Markus

**Comment by amirkhan81** [comment]
Hi! Thanks for the quick reply. I didn't realize it had been rewritten but after starting to build this project its pretty obvious...appreciate the updates in the future and obviously no expectation on timing, it was just a part of our default package installs and wanted to make sure I wasn't doing something wrong.

**Comment by KingDeadKnight** [comment]
Hello,

My company would like to update various projects to version 14 and we use this package a lot. In my spare time I've already had a look at adapting the client part to the new version if necessary. I still need to retrieve the name of the current node to display it in the title when necessary, and the url of the current node.

Quick question: I see that the repo is flagged hacktoberfest, but is it eligible for this year's umbraco hacktoberfest?

Thanks

**Comment by enkelmedia** [comment]
@KingDeadKnight, thanks for offering your help!

I think that the package as a part of Hacktoberfest last year and I've added a PR to the Umbraco Package repository for Hacktoberfest https://github.com/umbraco/Umbraco.Packages/pull/202 so it should be eligible for this year's umbraco Hacktoberfest once the PR is accepted.

I have another package that I've migrated to v14, the source can be found here: https://github.com/enkelmedia/TheDashboard, here is the client side specific "stuff" https://github.com/enkelmedia/TheDashboard/tree/v14/dev/src/Our.Umbraco.TheDashboard/Client

I think that this is much simpler but there are a couple of things that I would like to ensure:

* That we're using TypeScript (can probably copy the package.json, tsconfig, etc from The Dashboard as a starting point)
* That the client files goes in `SeoVisualizer/Client` (same pattern as for The Dashboard)

If you are up for creating a contribution I would be more than happy to work with you and merge it.

Oh, and reg. the URLs. I think that you need to consume some kind of context that would hold this information. Looks like you need the `UMB_DOCUMENT_WORKSPACE_CONTEXT` for the URLs (see code for the info tab here: https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts) and I suspect that you might be able to find the name there as well.

**Comment by enkelmedia** [comment]
I'll spend some time right away to setup the "foundation" and then any contributions can be targeted towards that new branch. Keep you posted.

**Comment by enkelmedia** [comment]
I've created a v14-branch now that contains the "foundation" for the editor. 

https://github.com/enkelmedia/Umbraco-SeoVisualizer/tree/v14

Not worked anything on the editor UI but I made some issues that someone can work on if they want.

✅ https://github.com/enkelmedia/Umbraco-SeoVisualizer/issues/31

✅ https://github.com/enkelmedia/Umbraco-SeoVisualizer/issues/32

Please keep me posted in the respective issues if you go ahead and work on any of them so that we can avoid double work.

Cheers!

**Comment by enkelmedia** [comment]
Hi again!

I went ahead and implemented the property editor and created a release candidate,

https://www.nuget.org/packages/UmbracoSeoVisualizer/14.0.0-rc1

Make sure to check the "Show pre-releases" checkbox to see this in Visual Studio.

There is one thing missing and that is https://github.com/enkelmedia/Umbraco-SeoVisualizer/issues/31 that I need to figure out. I've posted a question on discord about this and will wait for some feedback.

In the RC one would need to recondigure the data type and choose the "Seo Visualizer" property editor again as Umbraco will reconfigure it as a Label during startup.

**Comment by enkelmedia** [comment]
Just released a 2nd RC that now includes the migrations so that any data type using SeoVisualizer should "just work" after a upgrade from v13 to v14.

I've tested this with an upgrade from 13.5.1 to 14.3.0 - would love to hear your feedback.

https://www.nuget.org/packages/UmbracoSeoVisualizer/14.0.0-rc2

**Comment by enkelmedia** [comment]
Closing this as `14.0.0` has been out for a while.

https://marketplace.umbraco.com/package/umbracoseovisualizer
